version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '80:4000'
    links:
      - mongo
    environment: 
      - MONGODB_URI=mongodb://mongo:27017/docket
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - '27017:27017'
